name: test and deploy

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set-Up Node
        uses: actions/setup-node@v1
        with:
            node-version: "10.x"
      - run: yarn install
      - run: yarn lint
      - run: yarn test:unit
      - run: yarn build
